In [ ]:
import pandas as pd

# Load the dataset with latin1 encoding to handle special characters
try:
    df = pd.read_csv('APL_Logistics.csv', encoding='latin1')
    print('Dataset loaded successfully!')
    display(df.head())
except Exception as e:
    print(f'Error: {e}')

Dataset loaded successfully!

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Order Region,Order State,Order Status,Product Name,Product Price,Shipping Mode
0,DEBIT,6,4,159.69,472.45,Late delivery,1,9,Cardio Equipment,Brownsville,...,5,499.95,472.45,159.69,South Asia,Maharashtra,COMPLETE,Nike Men's Free 5.0+ Running Shoe,99.99,Standard Class
1,DEBIT,4,4,48.71,167.96,Shipping on time,0,29,Shop By Sport,Littleton,...,5,199.95,167.96,48.71,Central America,Cortés,ON_HOLD,Under Armour Girls' Toddler Spine Surge Runni,39.99,Standard Class
2,DEBIT,4,4,87.36,181.99,Shipping on time,0,48,Water Sports,Littleton,...,1,199.99,181.99,87.36,Central America,Cortés,ON_HOLD,Pelican Sunstream 100 Kayak,199.99,Standard Class
3,DEBIT,6,4,-41.89,175.99,Late delivery,1,48,Water Sports,Littleton,...,1,199.99,175.99,-41.89,East of USA,Nueva York,COMPLETE,Pelican Sunstream 100 Kayak,199.99,Standard Class
4,DEBIT,6,4,10.00,40.00,Late delivery,1,24,Women's Apparel,Littleton,...,1,50.00,40.00,10.00,East of USA,Nueva York,COMPLETE,Nike Men's Dri-FIT Victory Golf Polo,50.00,Standard Class

In [ ]:
import numpy as np

# Identifying the product name column (usually 'Product Name')
product_col = [col for col in df.columns if 'Product Name' in col]

if product_col:
    col_name = product_col[0]
    unique_products = df[col_name].unique()
    print(f"Found {len(unique_products)} unique products in column: '{col_name}'")
    print("\nFirst 20 product names:")
    display(unique_products[:20])
else:
    print("Could not find a 'Product Name' column. Here are all available columns:")
    print(df.columns.tolist())

Found 118 unique products in column: 'Product Name'

First 20 product names:

array(["Nike Men's Free 5.0+ Running Shoe",
       "Under Armour Girls' Toddler Spine Surge Runni",
       'Pelican Sunstream 100 Kayak',
       "Nike Men's Dri-FIT Victory Golf Polo",
       "Diamondback Women's Serene Classic Comfort Bi",
       "O'Brien Men's Neoprene Life Vest",
       'Field & Stream Sportsman 16 Gun Fire Safe',
       'Perfect Fitness Perfect Rip Deck',
       "Under Armour Kids' Mercenary Slide",
       "Nike Men's CJ Elite 2 TD Football Cleat",
       'Team Golf Texas Longhorns Putter Grip',
       'Team Golf St. Louis Cardinals Putter Grip',
       'Under Armour Hustle Storm Medium Duffle Bag',
       'Team Golf New England Patriots Putter Grip',
       "Glove It Women's Mod Oval 3-Zip Carry All Gol",
       'Team Golf Tennessee Volunteers Putter Grip', 'Total Gym 1400',
       "adidas Kids' F5 Messi FG Soccer Cleat",
       'Clicgear Rovic Cooler Bag',
       'Team Golf Pittsburgh Steelers Putter Grip'], dtype=object)

In [ ]:
# List the columns you want to remove here
columns_to_remove = ['Customer Fname', 'Customer Lname', 'Customer Street', 'Latitude', 'Longitude', 'Category Id', 'Department Id', 'Customer Id', 'Order Customer Id', 'Customer Zipcode', 'Product Name'] # Example columns

# Drop the columns. errors='ignore' prevents an error if the column was already deleted
df = df.drop(columns=columns_to_remove, errors='ignore')

print(f"Removed columns: {columns_to_remove}")
print(f"Remaining columns: {len(df.columns)}")
display(df.head())

Removed columns: ['Customer Fname', 'Customer Lname', 'Customer Street', 'Latitude', 'Longitude', 'Category Id', 'Department Id', 'Customer Id', 'Order Customer Id', 'Customer Zipcode', 'Product Name']
Remaining columns: 29

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Name,Customer City,Customer Country,...,Order Item Profit Ratio,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Order Region,Order State,Order Status,Product Price,Shipping Mode
0,DEBIT,6,4,159.69,472.45,Late delivery,1,Cardio Equipment,Brownsville,EE. UU.,...,0.34,5,499.95,472.45,159.69,South Asia,Maharashtra,COMPLETE,99.99,Standard Class
1,DEBIT,4,4,48.71,167.96,Shipping on time,0,Shop By Sport,Littleton,EE. UU.,...,0.29,5,199.95,167.96,48.71,Central America,Cortés,ON_HOLD,39.99,Standard Class
2,DEBIT,4,4,87.36,181.99,Shipping on time,0,Water Sports,Littleton,EE. UU.,...,0.48,1,199.99,181.99,87.36,Central America,Cortés,ON_HOLD,199.99,Standard Class
3,DEBIT,6,4,-41.89,175.99,Late delivery,1,Water Sports,Littleton,EE. UU.,...,-0.24,1,199.99,175.99,-41.89,East of USA,Nueva York,COMPLETE,199.99,Standard Class
4,DEBIT,6,4,10.00,40.00,Late delivery,1,Women's Apparel,Littleton,EE. UU.,...,0.25,1,50.00,40.00,10.00,East of USA,Nueva York,COMPLETE,50.00,Standard Class

In [ ]:
# Check for missing values
missing_data = df.isnull().sum()
if missing_data.any():
    print('Missing values found per column:')
    display(missing_data[missing_data > 0])
else:
    print('No missing values detected.')

No missing values detected.

In [ ]:
# Check for duplicate rows
duplicate_count = df.duplicated().sum()

if duplicate_count > 0:
    print(f'Found {duplicate_count} duplicate rows.')
    print('\nExample of duplicate rows:')
    display(df[df.duplicated()].head())
else:
    print('No duplicate rows found.')

Found 2 duplicate rows.

Example of duplicate rows:

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Name,Customer City,Customer Country,...,Order Item Profit Ratio,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Order Region,Order State,Order Status,Product Price,Shipping Mode
168152,TRANSFER,3,4,10.98,124.79,Advance shipping,0,Men's Footwear,Caguas,Puerto Rico,...,0.09,1,129.99,124.79,10.98,Central America,Cortés,PROCESSING,129.99,Standard Class
168823,DEBIT,6,4,123.46,251.96,Late delivery,1,Cleats,Caguas,Puerto Rico,...,0.49,5,299.95,251.96,123.46,Central America,Francisco Morazán,ON_HOLD,59.99,Standard Class

In [ ]:
# Remove duplicate rows
initial_count = len(df)
df = df.drop_duplicates()
final_count = len(df)

print(f"Rows before: {initial_count}")
print(f"Rows after: {final_count}")
print(f"Total rows removed: {initial_count - final_count}")

Rows before: 180519
Rows after: 180517
Total rows removed: 2

In [ ]:
(df['Days for shipping (real)'] < 0).sum()

np.int64(0)

In [ ]:
(df['Days for shipment (scheduled)'] < 0).sum()

np.int64(0)

In [ ]:
print(df['Shipping Mode'].unique())
print(df['Delivery Status'].unique())
print(df['Market'].unique())
print(df['Customer Segment'].unique())
print(df['Order Region'].unique())

['Standard Class' 'Same Day' 'First Class' 'Second Class']
['Late delivery' 'Shipping on time' 'Advance shipping' 'Shipping canceled']
['Pacific Asia' 'LATAM' 'USCA' 'Europe' 'Africa']
['Consumer' 'Home Office' 'Corporate']
['South Asia' 'Central America' 'East of USA' 'Southern Europe'
 'Western Europe' 'Oceania' 'South America' 'West Asia' 'West Africa'
 'Caribbean' 'US Center' 'Central Africa' 'Southeast Asia'
 'Northern Europe' 'Eastern Asia' 'South of USA' 'Southern Africa'
 'West of USA' 'Eastern Europe' 'Canada' 'East Africa' 'North Africa'
 'Central Asia']

In [ ]:
import pandas as pd

# Identify columns with string (object) data types
string_columns = df.select_dtypes(include=['object']).columns

for col in string_columns:
    # 1. Convert to string to avoid errors
    # 2. .strip() removes leading and trailing spaces
    # 3. .replace(r'\s+', ' ', regex=True) replaces multiple spaces with a single space
    df[col] = df[col].astype(str).str.strip().str.replace(r'\s+', ' ', regex=True)

print('Extra white spaces have been trimmed and normalized.')
# Verifying with the 'Order Region' column mentioned earlier
print('\nUnique values in Order Region:')
print(df['Order Region'].unique())

/tmp/ipykernel_1607/2913234120.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].astype(str).str.strip().str.replace(r'\s+', ' ', regex=True)
/tmp/ipykernel_1607/2913234120.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].astype(str).str.strip().str.replace(r'\s+', ' ', regex=True)
/tmp/ipykernel_1607/2913234120.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].astype(str).str.strip().str.replace(r'\s+', ' ', regex=True)
/tmp/ipykernel_1607/2913234120.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].astype(str).str.strip().str.replace(r'\s+', ' ', regex=True)
/tmp/ipykernel_1607/2913234120.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].astype(str).str.strip().str.replace(r'\s+', ' ', regex=True)
/tmp/ipykernel_1607/2913234120.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].astype(str).str.strip().str.replace(r'\s+', ' ', regex=True)
/tmp/ipykernel_1607/2913234120.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].astype(str).str.strip().str.replace(r'\s+', ' ', regex=True)
/tmp/ipykernel_1607/2913234120.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].astype(str).str.strip().str.replace(r'\s+', ' ', regex=True)
/tmp/ipykernel_1607/2913234120.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].astype(str).str.strip().str.replace(r'\s+', ' ', regex=True)
/tmp/ipykernel_1607/2913234120.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].astype(str).str.strip().str.replace(r'\s+', ' ', regex=True)
/tmp/ipykernel_1607/2913234120.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].astype(str).str.strip().str.replace(r'\s+', ' ', regex=True)
/tmp/ipykernel_1607/2913234120.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].astype(str).str.strip().str.replace(r'\s+', ' ', regex=True)
/tmp/ipykernel_1607/2913234120.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].astype(str).str.strip().str.replace(r'\s+', ' ', regex=True)
/tmp/ipykernel_1607/2913234120.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].astype(str).str.strip().str.replace(r'\s+', ' ', regex=True)

Extra white spaces have been trimmed and normalized.

Unique values in Order Region:
['South Asia' 'Central America' 'East of USA' 'Southern Europe'
 'Western Europe' 'Oceania' 'South America' 'West Asia' 'West Africa'
 'Caribbean' 'US Center' 'Central Africa' 'Southeast Asia'
 'Northern Europe' 'Eastern Asia' 'South of USA' 'Southern Africa'
 'West of USA' 'Eastern Europe' 'Canada' 'East Africa' 'North Africa'
 'Central Asia']

/tmp/ipykernel_1607/2913234120.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].astype(str).str.strip().str.replace(r'\s+', ' ', regex=True)

In [ ]:
from google.colab import files

# Save the cleaned DataFrame to a CSV file
file_name = 'cleaned_APL_Logistics.csv'
df.to_csv(file_name, index=False)

print(f'File saved as {file_name}')

# Automatically trigger a download of the file
files.download(file_name)

File saved as cleaned_APL_Logistics.csv

## Now we will do some changes in cleaned file

In [ ]:
import pandas as pd

df = pd.read_csv('cleaned_APL_Logistics.csv')
display(df.head())

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Name,Customer City,Customer Country,...,Order Item Profit Ratio,Order Item Quantity,Sales,Order Item Total,Order Profit Per Order,Order Region,Order State,Order Status,Product Price,Shipping Mode
0,DEBIT,6,4,159.69,472.45,Late delivery,1,Cardio Equipment,Brownsville,EE. UU.,...,0.34,5,499.95,472.45,159.69,South Asia,Maharashtra,COMPLETE,99.99,Standard Class
1,DEBIT,4,4,48.71,167.96,Shipping on time,0,Shop By Sport,Littleton,EE. UU.,...,0.29,5,199.95,167.96,48.71,Central America,Cortés,ON_HOLD,39.99,Standard Class
2,DEBIT,4,4,87.36,181.99,Shipping on time,0,Water Sports,Littleton,EE. UU.,...,0.48,1,199.99,181.99,87.36,Central America,Cortés,ON_HOLD,199.99,Standard Class
3,DEBIT,6,4,-41.89,175.99,Late delivery,1,Water Sports,Littleton,EE. UU.,...,-0.24,1,199.99,175.99,-41.89,East of USA,Nueva York,COMPLETE,199.99,Standard Class
4,DEBIT,6,4,10.00,40.00,Late delivery,1,Women's Apparel,Littleton,EE. UU.,...,0.25,1,50.00,40.00,10.00,East of USA,Nueva York,COMPLETE,50.00,Standard Class

In [ ]:
df['Delay_Gap'] = (
    df['Days for shipping (real)']
    - df['Days for shipment (scheduled)']
)

In [ ]:
def classify(delay):
    if delay < 0:
        return 'Early'
    elif delay == 0:
        return 'On Time'
    else:
        return 'Delayed'

df['Delivery_Class'] = df['Delay_Gap'].apply(classify)

In [ ]:
df['Delivery_Class'].value_counts()

Delivery_Class
Delayed    103399
Early       43365
On Time     33753
Name: count, dtype: int64

In [ ]:
def severity(x):
    if x <= 0:
        return 'No Delay'
    elif x <= 2:
        return 'Low'
    elif x <= 5:
        return 'Medium'
    else:
        return 'High'

df['Delay_Severity'] = df['Delay_Gap'].apply(severity)

In [ ]:
# Calculate negative counts for 'Days for shipping (real)'
negative_real_shipping_days = (df['Days for shipping (real)'] < 0).sum()
print(f"Negative count for 'Days for shipping (real)': {negative_real_shipping_days}")

Negative count for 'Days for shipping (real)': 0

In [ ]:
# Calculate negative counts for 'Days for shipment (scheduled)'
negative_scheduled_shipping_days = (df['Days for shipment (scheduled)'] < 0).sum()
print(f"Negative count for 'Days for shipment (scheduled)': {negative_scheduled_shipping_days}")

Negative count for 'Days for shipment (scheduled)': 0

In [ ]:
print('Unique values for Shipping Mode:')
print(df['Shipping Mode'].unique())

Unique values for Shipping Mode:
['Standard Class' 'Same Day' 'First Class' 'Second Class']

In [ ]:
print('\nUnique values for Delivery Status:')
print(df['Delivery Status'].unique())

Unique values for Delivery Status:
['Late delivery' 'Shipping on time' 'Advance shipping' 'Shipping canceled']

In [ ]:
pd.crosstab(
    df['Delivery_Class'],
    df['Late_delivery_risk']
)

Late_delivery_risk      0      1
Delivery_Class
Delayed              4423  98976
Early               43365      0
On Time             33753      0

In [ ]:
df['Market'].value_counts()

Market
LATAM           51592
Europe          50252
Pacific Asia    41260
USCA            25799
Africa          11614
Name: count, dtype: int64

In [ ]:
df['Customer Segment'].value_counts()

Customer Segment
Consumer       93503
Corporate      54788
Home Office    32226
Name: count, dtype: int64

In [ ]:
df['Order Region'].nunique()

23

In [ ]:
df['Order Country'].nunique()

164

In [ ]:
df.to_csv('APL_Logistics_Cleaned.csv', index=False)

In [ ]:
df = pd.read_csv('APL_Logistics_Cleaned.csv', encoding='utf-8')

In [ ]:
# Check for missing values in 'Order State'
missing_order_state = df['Order State'].isnull().sum()
print(f"Missing values in 'Order State': {missing_order_state}")

Missing values in 'Order State': 0

In [ ]:
# Check the data type of 'Order State'
order_state_dtype = df['Order State'].dtype
print(f"Data type of 'Order State': {order_state_dtype}")

Data type of 'Order State': object

In [ ]:
# Display some random samples of 'Order State' to visually inspect
print("\nRandom samples from 'Order State':")
display(df['Order State'].head(5))

Random samples from 'Order State':

0    Maharashtra
1         Cortés
2         Cortés
3     Nueva York
4     Nueva York
Name: Order State, dtype: object

In [ ]:
df.to_excel('APL_Logistics_Final.xlsx', index=False)