In [ ]:
!wget -O Atlantic_France.csv "https://drive.google.com/uc?export=download&id=1ZqeasA0AnD9ThgCwcFts68R7Ol86FPkJ"

--2026-10-15 06:04:41--  https://drive.google.com/uc?export=download&id=1ZqeasA0AnD9ThgCwcFts68R7Ol86FPkJ
Resolving drive.google.com (drive.google.com)... 142.251.108.113, 142.251.108.138, 142.251.108.100, ...
Connecting to drive.google.com (drive.google.com)|142.251.108.113|:443... connected.
HTTP request sent, awaiting response... 303 See Other
Location: https://drive.usercontent.google.com/download?id=1ZqeasA0AnD9ThgCwcFts68R7Ol86FPkJ&export=download [following]
--2026-10-15 06:04:41--  https://drive.usercontent.google.com/download?id=1ZqeasA0AnD9ThgCwcFts68R7Ol86FPkJ&export=download
Resolving drive.usercontent.google.com (drive.usercontent.google.com)... 142.251.121.132, 2607:f8b0:4023:80b::84
Connecting to drive.usercontent.google.com (drive.usercontent.google.com)|142.251.121.132|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3605408 (3.4M) [application/octet-stream]
Saving to: ‘Atlantic_France.csv’

Atlantic_France.csv 100%[===================>]   3.44M  --.-KB/s    in 0.1s

2026-10-15 06:04:42 (27.0 MB/s) - ‘Atlantic_France.csv’ saved [3605408/3605408]

In [ ]:
import pandas as pd

df = pd.read_csv("Atlantic_France.csv")
df.head()

,date,position,song,artist,popularity,duration_ms,album_type,total_tracks,is_explicit,album_cover_url
0,18-05-2024,1,LA RUE,No Limit & Gazo & Damso,72,225137,single,1,True,https://i.scdn.co/image/ab67616d0000b27384f245...
1,18-05-2024,2,C'est carré le S,Naps,74,201533,album,22,False,https://i.scdn.co/image/ab67616d0000b27348f7c1...
2,18-05-2024,3,Freestyle LVL UP 1,Ninho,76,114182,single,1,True,https://i.scdn.co/image/ab67616d0000b273fbe613...
3,18-05-2024,4,Bolide allemand,SDM,79,176746,album,15,True,https://i.scdn.co/image/ab67616d0000b273455e89...
4,18-05-2024,5,Freestyle LVL UP 2,Ninho,71,149064,single,1,True,https://i.scdn.co/image/ab67616d0000b27351f1cb...

In [ ]:
df[df["popularity"] == 0]

,date,position,song,artist,popularity,duration_ms,album_type,total_tracks,is_explicit,album_cover_url
3603,29-07-2024,4,HYAENA,Travis Scott,0,222085,album,19,True,https://i.scdn.co/image/ab67616d0000b273881d8d...
3604,29-07-2024,5,THANK GOD,Travis Scott,0,184888,album,19,True,https://i.scdn.co/image/ab67616d0000b273881d8d...
3605,29-07-2024,6,FE!N,Travis Scott,0,191700,album,19,True,https://i.scdn.co/image/ab67616d0000b273881d8d...
3606,29-07-2024,7,MY EYES,Travis Scott,0,251249,album,19,True,https://i.scdn.co/image/ab67616d0000b273881d8d...
3608,29-07-2024,9,MODERN JAM,Travis Scott,0,255412,album,19,True,https://i.scdn.co/image/ab67616d0000b273881d8d...
...,...,...,...,...,...,...,...,...,...,...
17753,09-05-2025,4,Gata Only (Mashup),Dj Agus Lima,0,215400,album,9,False,https://i.scdn.co/image/ab67616d0000b273068b0f...
18179,17-05-2025,30,Cannelloni,SCH,0,198146,single,1,True,https://i.scdn.co/image/ab67616d0000b2738bf2a4...
18229,18-05-2025,30,Cannelloni,SCH,0,198146,single,1,True,https://i.scdn.co/image/ab67616d0000b2738bf2a4...
19655,16-06-2025,6,Hakayet,VEN1,0,158208,single,1,True,https://i.scdn.co/image/ab67616d0000b27313295a...
25472,12-10-2025,23,Minimum ça,Dr. Yaro,0,149811,single,1,False,https://i.scdn.co/image/ab67616d0000b273d39b05...

In [ ]:
df.shape

(27800, 10)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27800 entries, 0 to 27799
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   date             27800 non-null  object
 1   position         27800 non-null  int64
 2   song             27799 non-null  object
 3   artist           27800 non-null  object
 4   popularity       27800 non-null  int64
 5   duration_ms      27800 non-null  int64
 6   album_type       27800 non-null  object
 7   total_tracks     27800 non-null  int64
 8   is_explicit      27800 non-null  bool
 9   album_cover_url  27800 non-null  object
dtypes: bool(1), int64(4), object(5)
memory usage: 1.9+ MB

In [ ]:
df.describe()

           position    popularity    duration_ms  total_tracks
count  27800.000000  27800.000000   27800.000000  27800.000000
mean      25.500000     76.645108  185474.848165      8.999856
std       14.431129     11.570874   32436.845058      8.140060
min        1.000000      0.000000       0.000000      1.000000
25%       13.000000     71.000000  165586.000000      1.000000
50%       25.500000     75.000000  180000.000000     10.000000
75%       38.000000     83.000000  207733.000000     15.000000
max       50.000000    100.000000  547413.000000    119.000000

In [ ]:
df.isnull().sum()

date               0
position           0
song               1
artist             0
popularity         0
duration_ms        0
album_type         0
total_tracks       0
is_explicit        0
album_cover_url    0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(19)

In [ ]:

# Step 2: Inspect dates and duplicate records

# Convert date column to datetime
df['date'] = pd.to_datetime(df['date'], dayfirst=True, errors='coerce')

print("Date data type:", df['date'].dtype)
print("Invalid dates:", df['date'].isna().sum())

print("\nDate range:")
print("Earliest date:", df['date'].min())
print("Latest date:", df['date'].max())

print("\nNumber of unique dates:", df['date'].nunique())

print("\nExact duplicate rows:", int(df.duplicated().sum()))

# Display duplicate records for inspection
display(df[df.duplicated(keep=False)].sort_values(
    by=['date', 'position']
).head(20))

# Inspect the missing song record
print("\nRecord with missing song:")
display(df[df['song'].isna()])

Date data type: datetime64[ns]
Invalid dates: 0

Date range:
Earliest date: 2024-05-18 00:00:00
Latest date: 2025-11-27 00:00:00

Number of unique dates: 555

Exact duplicate rows: 19

,date,position,song,artist,popularity,duration_ms,album_type,total_tracks,is_explicit,album_cover_url
14350,2025-03-01,1,Pyramide,Werenoi,78,208405,album,17,True,https://i.scdn.co/image/ab67616d0000b273cb7db7...
14400,2025-03-01,1,Pyramide,Werenoi,78,208405,album,17,True,https://i.scdn.co/image/ab67616d0000b273cb7db7...
14351,2025-03-01,2,Petit génie,Jungeli & Imen Es & Alonzo,84,217259,single,1,True,https://i.scdn.co/image/ab67616d0000b2737b6ae1...
14401,2025-03-01,2,Petit génie,Jungeli & Imen Es & Alonzo,84,217259,single,1,True,https://i.scdn.co/image/ab67616d0000b2737b6ae1...
14352,2025-03-01,3,Ceux qu'on était,Pierre Garnier,82,174106,single,1,False,https://i.scdn.co/image/ab67616d0000b27398855c...
14402,2025-03-01,3,Ceux qu'on était,Pierre Garnier,82,174106,single,1,False,https://i.scdn.co/image/ab67616d0000b27398855c...
14355,2025-03-01,6,Beautiful Things,Benson Boone,100,180304,single,1,False,https://i.scdn.co/image/ab67616d0000b273f2a919...
14405,2025-03-01,6,Beautiful Things,Benson Boone,100,180304,single,1,False,https://i.scdn.co/image/ab67616d0000b273f2a919...
14356,2025-03-01,7,MAMI WATA,Gazo & Tiakola,79,233240,album,12,True,https://i.scdn.co/image/ab67616d0000b2737dfe25...
14406,2025-03-01,7,MAMI WATA,Gazo & Tiakola,79,233240,album,12,True,https://i.scdn.co/image/ab67616d0000b2737dfe25...
14357,2025-03-01,8,Tu connais,Werenoi,74,169000,album,7,True,https://i.scdn.co/image/ab67616d0000b2737fed90...
14407,2025-03-01,8,Tu connais,Werenoi,74,169000,album,7,True,https://i.scdn.co/image/ab67616d0000b2737fed90...
14360,2025-03-01,11,Maudit,Werenoi,73,197568,album,17,True,https://i.scdn.co/image/ab67616d0000b273cb7db7...
14410,2025-03-01,11,Maudit,Werenoi,73,197568,album,17,True,https://i.scdn.co/image/ab67616d0000b273cb7db7...
14361,2025-03-01,12,Houdini,Dua Lipa,95,185917,single,1,False,https://i.scdn.co/image/ab67616d0000b273001d57...
14411,2025-03-01,12,Houdini,Dua Lipa,95,185917,single,1,False,https://i.scdn.co/image/ab67616d0000b273001d57...
14364,2025-03-01,15,Temps en temps,Zola & Koba LaD,64,153649,album,15,True,https://i.scdn.co/image/ab67616d0000b273353d56...
14414,2025-03-01,15,Temps en temps,Zola & Koba LaD,64,153649,album,15,True,https://i.scdn.co/image/ab67616d0000b273353d56...
14365,2025-03-01,16,greedy,Tate McRae,99,131872,single,1,True,https://i.scdn.co/image/ab67616d0000b27322fd80...
14415,2025-03-01,16,greedy,Tate McRae,99,131872,single,1,True,https://i.scdn.co/image/ab67616d0000b27322fd80...

Record with missing song:

,date,position,song,artist,popularity,duration_ms,album_type,total_tracks,is_explicit,album_cover_url
13001,2025-02-02,2,NaN,Lavern,0,0,single,5,False,https://i.scdn.co/image/ab67616d0000b273eb5e3a...

In [ ]:
display(df[df['song'].isna()].T)

                                                             13001
date                                           2025-02-02 00:00:00
position                                                         2
song                                                           NaN
artist                                                      Lavern
popularity                                                       0
duration_ms                                                      0
album_type                                                  single
total_tracks                                                     5
is_explicit                                                  False
album_cover_url  https://i.scdn.co/image/ab67616d0000b273eb5e3a...

In [ ]:

# Inspect all records for the same date
display(
    df[df['date'] == '2025-02-02']
    .sort_values('position')
    .head(5)
)

# Inspect records for the same artist
display(
    df[df['artist'].str.strip().str.lower() == 'lavern']
    .sort_values(['date', 'position'])
    .head(10)
)

,date,position,song,artist,popularity,duration_ms,album_type,total_tracks,is_explicit,album_cover_url
13000,2025-02-02,1,Petit génie,Jungeli & Imen Es & Alonzo,84,217259,single,1,True,https://i.scdn.co/image/ab67616d0000b2737b6ae1...
13001,2025-02-02,2,NaN,Lavern,0,0,single,5,False,https://i.scdn.co/image/ab67616d0000b273eb5e3a...
13002,2025-02-02,3,Ça mène à rien,PLK,74,198773,album,11,True,https://i.scdn.co/image/ab67616d0000b2735f47f0...
13003,2025-02-02,4,FLASHBACK,Favé,79,176120,album,15,True,https://i.scdn.co/image/ab67616d0000b273bed20c...
13004,2025-02-02,5,Temps en temps,Zola & Koba LaD,67,153653,album,11,True,https://i.scdn.co/image/ab67616d0000b273daa83e...

,date,position,song,artist,popularity,duration_ms,album_type,total_tracks,is_explicit,album_cover_url
13001,2025-02-02,2,NaN,Lavern,0,0,single,5,False,https://i.scdn.co/image/ab67616d0000b273eb5e3a...

In [ ]:
df = df.dropna(subset=['song'])

In [ ]:

# Check exact duplicate rows

print("Current dataset shape:", df.shape)
print("Exact duplicate rows:", int(df.duplicated().sum()))

# Display duplicate records for inspection
display(
    df[df.duplicated(keep=False)]
    .sort_values(by=['date', 'position'])
)

Current dataset shape: (27799, 10)
Exact duplicate rows: 19

,date,position,song,artist,popularity,duration_ms,album_type,total_tracks,is_explicit,album_cover_url
14350,2025-03-01,1,Pyramide,Werenoi,78,208405,album,17,True,https://i.scdn.co/image/ab67616d0000b273cb7db7...
14400,2025-03-01,1,Pyramide,Werenoi,78,208405,album,17,True,https://i.scdn.co/image/ab67616d0000b273cb7db7...
14351,2025-03-01,2,Petit génie,Jungeli & Imen Es & Alonzo,84,217259,single,1,True,https://i.scdn.co/image/ab67616d0000b2737b6ae1...
14401,2025-03-01,2,Petit génie,Jungeli & Imen Es & Alonzo,84,217259,single,1,True,https://i.scdn.co/image/ab67616d0000b2737b6ae1...
14352,2025-03-01,3,Ceux qu'on était,Pierre Garnier,82,174106,single,1,False,https://i.scdn.co/image/ab67616d0000b27398855c...
14402,2025-03-01,3,Ceux qu'on était,Pierre Garnier,82,174106,single,1,False,https://i.scdn.co/image/ab67616d0000b27398855c...
14355,2025-03-01,6,Beautiful Things,Benson Boone,100,180304,single,1,False,https://i.scdn.co/image/ab67616d0000b273f2a919...
14405,2025-03-01,6,Beautiful Things,Benson Boone,100,180304,single,1,False,https://i.scdn.co/image/ab67616d0000b273f2a919...
14356,2025-03-01,7,MAMI WATA,Gazo & Tiakola,79,233240,album,12,True,https://i.scdn.co/image/ab67616d0000b2737dfe25...
14406,2025-03-01,7,MAMI WATA,Gazo & Tiakola,79,233240,album,12,True,https://i.scdn.co/image/ab67616d0000b2737dfe25...
14357,2025-03-01,8,Tu connais,Werenoi,74,169000,album,7,True,https://i.scdn.co/image/ab67616d0000b2737fed90...
14407,2025-03-01,8,Tu connais,Werenoi,74,169000,album,7,True,https://i.scdn.co/image/ab67616d0000b2737fed90...
14360,2025-03-01,11,Maudit,Werenoi,73,197568,album,17,True,https://i.scdn.co/image/ab67616d0000b273cb7db7...
14410,2025-03-01,11,Maudit,Werenoi,73,197568,album,17,True,https://i.scdn.co/image/ab67616d0000b273cb7db7...
14361,2025-03-01,12,Houdini,Dua Lipa,95,185917,single,1,False,https://i.scdn.co/image/ab67616d0000b273001d57...
14411,2025-03-01,12,Houdini,Dua Lipa,95,185917,single,1,False,https://i.scdn.co/image/ab67616d0000b273001d57...
14364,2025-03-01,15,Temps en temps,Zola & Koba LaD,64,153649,album,15,True,https://i.scdn.co/image/ab67616d0000b273353d56...
14414,2025-03-01,15,Temps en temps,Zola & Koba LaD,64,153649,album,15,True,https://i.scdn.co/image/ab67616d0000b273353d56...
14365,2025-03-01,16,greedy,Tate McRae,99,131872,single,1,True,https://i.scdn.co/image/ab67616d0000b27322fd80...
14415,2025-03-01,16,greedy,Tate McRae,99,131872,single,1,True,https://i.scdn.co/image/ab67616d0000b27322fd80...
14366,2025-03-01,17,Chemin d'or,Werenoi,78,212093,album,19,True,https://i.scdn.co/image/ab67616d0000b2739d74d3...
14416,2025-03-01,17,Chemin d'or,Werenoi,78,212093,album,19,True,https://i.scdn.co/image/ab67616d0000b2739d74d3...
14368,2025-03-01,19,Popcorn Salé,SANTA,78,238653,single,1,False,https://i.scdn.co/image/ab67616d0000b273215b11...
14418,2025-03-01,19,Popcorn Salé,SANTA,78,238653,single,1,False,https://i.scdn.co/image/ab67616d0000b273215b11...
14379,2025-03-01,30,Ça mène à rien,PLK,75,198773,album,11,True,https://i.scdn.co/image/ab67616d0000b2735f47f0...
14429,2025-03-01,30,Ça mène à rien,PLK,75,198773,album,11,True,https://i.scdn.co/image/ab67616d0000b2735f47f0...
14388,2025-03-01,39,Solitaire,Werenoi,75,146440,album,14,True,https://i.scdn.co/image/ab67616d0000b27311b232...
14438,2025-03-01,39,Solitaire,Werenoi,75,146440,album,14,True,https://i.scdn.co/image/ab67616d0000b27311b232...
14391,2025-03-01,42,La symphonie des éclairs,Zaho de Sagazan,73,198789,album,14,False,https://i.scdn.co/image/ab67616d0000b273e89bee...
14441,2025-03-01,42,La symphonie des éclairs,Zaho de Sagazan,73,198789,album,14,False,https://i.scdn.co/image/ab67616d0000b273e89bee...
14392,2025-03-01,43,Avec classe (feat. Aya Nakamura & Trinix),Corneille & Aya Nakamura & Trinix,74,186071,single,1,False,https://i.scdn.co/image/ab67616d0000b273bc7413...
14442,2025-03-01,43,Avec classe (feat. Aya Nakamura & Trinix),Corneille & Aya Nakamura & Trinix,74,186071,single,1,False,https://i.scdn.co/image/ab67616d0000b273bc7413...
14393,2025-03-01,44,Hypé,Aya Nakamura,76,157053,single,1,False,https://i.scdn.co/image/ab67616d0000b27343d858...
14443,2025-03-01,44,Hypé,Aya Nakamura,76,157053,single,1,False,https://i.scdn.co/image/ab67616d0000b27343d858...
14394,2025-03-01,45,Whatever,Kygo & Ava Max,91,178273,single,1,False,https://i.scdn.co/image/ab67616d0000b2734d9144...
14444,2025-03-01,45,Whatever,Kygo & Ava Max,91,178273,single,1,False,https://i.scdn.co/image/ab67616d0000b2734d9144...
14398,2025-03-01,49,Bécane - A COLORS SHOW,Yamê,86,182440,single,1,True,https://i.scdn.co/image/ab67616d0000b2737dfba3...
14448,2025-03-01,49,Bécane - A COLORS SHOW,Yamê,86,182440,single,1,True,https://i.scdn.co/image/ab67616d0000b2737dfba3...

In [ ]:
df = df.drop_duplicates()

In [ ]:
# Remove the inconsistent date snapshot
df = df[df['date'] != pd.Timestamp('2025-03-01')]

print("Dataset shape:", df.shape)
print("Rows on 1 March 2025:", (df['date'] == pd.Timestamp('2025-03-01')).sum())

Dataset shape: (27699, 10)
Rows on 1 March 2025: 0

In [ ]:

# Final data-quality checks

print("Dataset shape:", df.shape)

print("\nMissing values:")
print(df.isna().sum())

print("\nExact duplicate rows:", int(df.duplicated().sum()))

print("\nUnique dates:", df['date'].nunique())

print("\nRows per date (summary):")
print(df.groupby('date').size().describe())

print("\nRows where position is outside 1–50:",
      (~df['position'].between(1, 50)).sum())

print("\nZero or negative duration:",
      (df['duration_ms'] <= 0).sum())

print("\nPopularity outside 0–100:",
      (~df['popularity'].between(0, 100)).sum())

print("\nAlbum types:")
print(df['album_type'].value_counts(dropna=False))

Dataset shape: (27699, 10)

Missing values:
date               0
position           0
song               0
artist             0
popularity         0
duration_ms        0
album_type         0
total_tracks       0
is_explicit        0
album_cover_url    0
dtype: int64

Exact duplicate rows: 0

Unique dates: 554

Rows per date (summary):
count    554.000000
mean      49.998195
std        0.042486
min       49.000000
25%       50.000000
50%       50.000000
75%       50.000000
max       50.000000
dtype: float64

Rows where position is outside 1–50: 0

Zero or negative duration: 0

Popularity outside 0–100: 0

Album types:
album_type
album          14647
single         13043
compilation        9
Name: count, dtype: int64

In [ ]:
daily_counts = df.groupby('date').size()

In [ ]:
display(daily_counts[daily_counts != 50].rename("row_count").to_frame())

            row_count
date
2025-02-02         49

In [ ]:
# Feature engineering

# Convert duration from milliseconds to minutes
df['duration_minutes'] = (df['duration_ms'] / 60000).round(2)

# Group playlist rankings
df['rank_band'] = pd.cut(
    df['position'],
    bins=[0, 10, 20, 30, 40, 50],
    labels=[
        'Top 10',
        '11–20',
        '21–30',
        '31–40',
        '41–50'
    ]
)

print("Updated dataset shape:", df.shape)

display(
    df[['date', 'position', 'song', 'duration_minutes', 'rank_band']].head()
)

Updated dataset shape: (27699, 12)

        date  position                song  duration_minutes rank_band
0 2024-05-18         1              LA RUE              3.75    Top 10
1 2024-05-18         2    C'est carré le S              3.36    Top 10
2 2024-05-18         3  Freestyle LVL UP 1              1.90    Top 10
3 2024-05-18         4     Bolide allemand              2.95    Top 10
4 2024-05-18         5  Freestyle LVL UP 2              2.48    Top 10

In [ ]:
# cleaned dataset file

df.to_csv('Atlantic_France_Cleaned.csv', index=False)